apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    color: {{ .Values.labels.appcolor}}
{{ include "sampleApp.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    instance-release: {{ .Release.Name }}
